#:include 'config.fypp'
#:if not defined('VISC_ORDER')
  #:set VISC_ORDER = ORDER
#:endif
#:if not defined('VISC_STENCIL')
  #:set VISC_STENCIL = 'Central'
#:endif
#:set is_les = (VISC == 'LES')
#:set base_suf = "_in"
#:if VISC_ORDER == 2
module calc_visc_high_internal
end module calc_visc_high_internal
#:else
module calc_visc_high_internal
  use mod_globals, only : gamma, R, Pr, Prt, dt, threadsEv, threadsFv, threadsGv
  use mod_constant, only : id_visc, Cp, gamma_1, Cp_over_Pr, one_third, two_third, one_twelfth
  #:if VISC_ORDER == 4
  use load_smem_visc_cent4
  #:elif VISC_STENCIL == 'ME4Base'
  use load_smem_visc_me4_base
  #:else
  use load_smem_visc_cent6
  #:endif
  implicit none
  private
  public calc_Ev${VISC_ORDER}$_in, calc_Fv${VISC_ORDER}$_in, calc_Gv${VISC_ORDER}$_in, &
         calc_Ev${VISC_ORDER}$_in_koff, calc_Fv${VISC_ORDER}$_in_koff, calc_Gv${VISC_ORDER}$_in_koff
  real(8), parameter :: one_24 = 1.d0 / 24.d0
contains
  #:if VISC_ORDER == 4
  #:include 'calc_visc_cent.f90.fypp'
  #:elif VISC_STENCIL == 'ME4Base'
  include 'calc_visc_me4_base.f90'
  #:else
  #:include 'calc_visc_cent.f90.fypp'
  #:endif

#:for is_koff in [False, True]
  #:set suf = base_suf
  #:if is_koff
    #:set suf = suf + "_koff"
  #:endif
  attributes(global) subroutine calc_Ev${VISC_ORDER}$${suf}$(nx, ny, nz, dx, dy, dz, Q, T, mu, &
    #:if is_les
      mut, qc2, &
    #:endif
    #:if is_koff
      k_lo, k_hi, &
    #:endif
    E)
    integer, intent(in), value                 :: nx
    integer, intent(in), value                 :: ny
    integer, intent(in), value                 :: nz
    real(8), intent(in), device, contiguous    :: dx(nx-1)
    real(8), intent(in), device, contiguous    :: dy(ny-1)
    real(8), intent(in), device, contiguous    :: dz(nz-1)
    real(8), intent(in), device, contiguous    :: Q(nx,5,ny,nz)
    real(8), intent(in), device, contiguous    :: T(nx,ny,nz)
    real(8), intent(in), device, contiguous    :: mu(nx,ny,nz)
    #:if is_les
    real(8), intent(in), device, contiguous    :: mut(nx,ny,nz)
    real(8), intent(in), device, contiguous    :: qc2(nx,ny,nz)
    #:endif
    real(8), intent(inout), device, contiguous :: E(5,nx-1,ny-2,nz-2)
    #:if is_koff
    integer, intent(in), value                 :: k_lo
    integer, intent(in), value                 :: k_hi
    #:endif
    #:if VISC_ORDER == 4
    integer, parameter :: io_v = 1
    #:else
    integer, parameter :: io_v = 2
    #:endif
    integer, parameter :: sx = threadsEv%x + 2*io_v + 1
    integer, parameter :: sy = threadsEv%y
    integer, parameter :: sz = threadsEv%z
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  u
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  v
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  w
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: uy
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: vy
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: uz
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: wz
    integer i, j, k, it, jt, kt, ii, idx, offset_yz
    real(8) :: txx, txy, txz, utxx, vtxy, wtxz, kTx
    #:if is_les
    real(8) Hsgs
    #:endif
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    #:if is_koff
    k  = (blockIdx%z-1)*blockDim%z + kt + k_lo - 1
    #:else
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    #:endif
    offset_yz = (jt-1)*sx + (kt-1)*sx*sy
    #:if VISC_ORDER == 4
    call load_smem_visc_cent4_x(it, jt, kt, j, k, nx, ny, nz, dy, dz, Q, u, v, w, uy, vy, uz, wz)
    #:elif VISC_STENCIL == 'ME4Base'
    call load_smem_visc_me4_base_x(it, jt, kt, j, k, nx, ny, nz, dy, dz, Q, u, v, w, uy, vy, uz, wz)
    #:else
    call load_smem_visc_cent6_x(it, jt, kt, j, k, nx, ny, nz, dy, dz, Q, u, v, w, uy, vy, uz, wz)
    #:endif
    i  = (blockIdx%x-1)*blockDim%x + it
    idx = it + offset_yz
    #:if is_koff
    if (nx-1 < i .or. ny-1 < j .or. k_hi < k) return
    #:else
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return
    #:endif
    #:if VISC_ORDER == 4
    if (2 <= i .and. i <= nx-2 .and. 3 <= j .and. j <= ny-2 .and. 3 <= k .and. k <= nz-2) then
      block
        real(8) :: mu4(4)
        #:if is_les
        real(8) :: mut4(4)
        mut4(:) = mut(i-1:i+2, j, k)
        #:endif
        mu4(:) = mu(i-1:i+2, j, k)
        kTx = Cp_over_Pr * interp4(mu4) * diff4(dx(i), T(i-1:i+2, j, k))
        #:if is_les
        call calc_tau_straight_LES(mu4, mut4, u(idx-1:idx+2), vy(idx-1:idx+2), wz(idx-1:idx+2), dx(i), txx, utxx)
        call calc_tau_cross_LES(mu4, mut4, v(idx-1:idx+2), uy(idx-1:idx+2), dx(i), txy, vtxy)
        call calc_tau_cross_LES(mu4, mut4, w(idx-1:idx+2), uz(idx-1:idx+2), dx(i), txz, wtxz)
        block
          real(8) :: H(4)
          H(:) = Cp * T(i-1:i+2,j,k) + 0.5d0 * (u(idx-1:idx+2)**2 + v(idx-1:idx+2)**2 + w(idx-1:idx+2)**2) + qc2(i-1:i+2,j,k)
          Hsgs = -interp4(mut4) * diff4(dx(i), H) / Prt
        end block
        #:else
        call calc_tau_straight(mu4, u(idx-1:idx+2), vy(idx-1:idx+2), wz(idx-1:idx+2), dx(i), txx, utxx)
        call calc_tau_cross(mu4, v(idx-1:idx+2), uy(idx-1:idx+2), dx(i), txy, vtxy)
        call calc_tau_cross(mu4, w(idx-1:idx+2), uz(idx-1:idx+2), dx(i), txz, wtxz)
        #:endif
        E(2,i,j-1,k-1) = E(2,i,j-1,k-1) - txx
        E(3,i,j-1,k-1) = E(3,i,j-1,k-1) - txy
        E(4,i,j-1,k-1) = E(4,i,j-1,k-1) - txz
        E(5,i,j-1,k-1) = E(5,i,j-1,k-1) - (utxx + vtxy + wtxz + kTx &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:elif VISC_STENCIL == 'ME4Base'
    if (3 <= i .and. i <= nx-3 .and. 3 <= j .and. j <= ny-2 .and. 3 <= k .and. k <= nz-2) then
      block
        real(8) :: mu3(3)
        #:if is_les
        real(8) :: mut3(3)
        mut3(:) = 0.0625d0 * (9.d0 * (mut(i-1:i+1,j,k) + mut(i:i+2,j,k)) - (mut(i-2:i,j,k) + mut(i+1:i+3,j,k)))
        #:endif
        mu3(:)  = 0.0625d0 * (9.d0 * ( mu(i-1:i+1,j,k) +  mu(i:i+2,j,k)) - ( mu(i-2:i,j,k) +  mu(i+1:i+3,j,k)))
        block ! dQdx
          real(8) :: kTx3(3)
          kTx3(:) = Cp_over_Pr * mu3(:) * &
                    (1.125d0 * (-T(i-1:i+1,j,k) + T(i:i+2,j,k)) - (-T(i-2:i,j,k) + T(i+1:i+3,j,k)) * one_24) * dx(i)
          kTx     = flux4(kTx3(:))
        end block
        #:if is_les
        call calc_tau_straight_LES(mu3, mut3, u(idx-2:idx+3), vy(idx-2:idx+3), wz(idx-2:idx+3), dx(i), txx, utxx)
        call calc_tau_cross_LES(mu3, mut3, v(idx-2:idx+3), uy(idx-2:idx+3), dx(i), txy, vtxy)
        call calc_tau_cross_LES(mu3, mut3, w(idx-2:idx+3), uz(idx-2:idx+3), dx(i), txz, wtxz)
        block
          real(8) :: H(4)
          H(:) = Cp * T(i-1:i+2,j,k) + 0.5d0 * (u(idx-1:idx+2)**2 + v(idx-1:idx+2)**2 + w(idx-1:idx+2)**2) + qc2(i-1:i+2,j,k)
          Hsgs = -flux4(mut3) * (1.125d0 * (-H(2) + H(3)) - (-H(1) + H(4)) * one_24) * dx(i) / Prt
        end block
        #:else
        call calc_tau_straight(mu3, u(idx-2:idx+3), vy(idx-2:idx+3), wz(idx-2:idx+3), dx(i), txx, utxx)
        call calc_tau_cross(mu3, v(idx-2:idx+3), uy(idx-2:idx+3), dx(i), txy, vtxy)
        call calc_tau_cross(mu3, w(idx-2:idx+3), uz(idx-2:idx+3), dx(i), txz, wtxz)
        #:endif
        E(2,i,j-1,k-1) = E(2,i,j-1,k-1) - txx
        E(3,i,j-1,k-1) = E(3,i,j-1,k-1) - txy
        E(4,i,j-1,k-1) = E(4,i,j-1,k-1) - txz
        E(5,i,j-1,k-1) = E(5,i,j-1,k-1) - (utxx + vtxy + wtxz + kTx &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:else
    if (3 <= i .and. i <= nx-3 .and. 4 <= j .and. j <= ny-3 .and. 4 <= k .and. k <= nz-3) then
      block
        real(8) :: mu6(6)
        #:if is_les
        real(8) :: mut6(6)
        mut6(:) = mut(i-2:i+3, j, k)
        #:endif
        mu6(:) = mu(i-2:i+3, j, k)
        kTx = Cp_over_Pr * interp6(mu6) * diff6(dx(i), T(i-2:i+3, j, k))
        #:if is_les
        call calc_tau_straight_LES(mu6, mut6, u(idx-2:idx+3), vy(idx-2:idx+3), wz(idx-2:idx+3), dx(i), txx, utxx)
        call calc_tau_cross_LES(mu6, mut6, v(idx-2:idx+3), uy(idx-2:idx+3), dx(i), txy, vtxy)
        call calc_tau_cross_LES(mu6, mut6, w(idx-2:idx+3), uz(idx-2:idx+3), dx(i), txz, wtxz)
        block
          real(8) :: H(6)
          H(:) = Cp * T(i-2:i+3,j,k) + 0.5d0 * (u(idx-2:idx+3)**2 + v(idx-2:idx+3)**2 + w(idx-2:idx+3)**2) + qc2(i-2:i+3,j,k)
          Hsgs = -interp6(mut6) * diff6(dx(i), H) / Prt
        end block
        #:else
        call calc_tau_straight(mu6, u(idx-2:idx+3), vy(idx-2:idx+3), wz(idx-2:idx+3), dx(i), txx, utxx)
        call calc_tau_cross(mu6, v(idx-2:idx+3), uy(idx-2:idx+3), dx(i), txy, vtxy)
        call calc_tau_cross(mu6, w(idx-2:idx+3), uz(idx-2:idx+3), dx(i), txz, wtxz)
        #:endif
        E(2,i,j-1,k-1) = E(2,i,j-1,k-1) - txx
        E(3,i,j-1,k-1) = E(3,i,j-1,k-1) - txy
        E(4,i,j-1,k-1) = E(4,i,j-1,k-1) - txz
        E(5,i,j-1,k-1) = E(5,i,j-1,k-1) - (utxx + vtxy + wtxz + kTx &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:endif
    endif
  end subroutine calc_Ev${VISC_ORDER}$${suf}$
#:endfor


#:for is_koff in [False, True]
  #:set suf = base_suf
  #:if is_koff
    #:set suf = suf + "_koff"
  #:endif
  attributes(global) subroutine calc_Fv${VISC_ORDER}$${suf}$(nx, ny, nz, dx, dy, dz, Q, T, mu, &
    #:if is_les
      mut, qc2, &
    #:endif
    #:if is_koff
      k_lo, k_hi, &
    #:endif
    F)
    integer, intent(in), value                 :: nx
    integer, intent(in), value                 :: ny
    integer, intent(in), value                 :: nz
    real(8), intent(in), device, contiguous    :: dx(nx-1)
    real(8), intent(in), device, contiguous    :: dy(ny-1)
    real(8), intent(in), device, contiguous    :: dz(nz-1)
    real(8), intent(in), device, contiguous    :: Q(nx,5,ny,nz)
    real(8), intent(in), device, contiguous    :: T(nx,ny,nz)
    real(8), intent(in), device, contiguous    :: mu(nx,ny,nz)
    #:if is_les
    real(8), intent(in), device, contiguous    :: mut(nx,ny,nz)
    real(8), intent(in), device, contiguous    :: qc2(nx,ny,nz)
    #:endif
    real(8), intent(inout), device, contiguous :: F(5,nx-2,ny-1,nz-2)
    #:if is_koff
    integer, intent(in), value                 :: k_lo
    integer, intent(in), value                 :: k_hi
    #:endif
    #:if VISC_ORDER == 4
    integer, parameter :: io_v = 1
    #:else
    integer, parameter :: io_v = 2
    #:endif
    integer, parameter :: sx = threadsFv%x
    integer, parameter :: sy = threadsFv%y + 2*io_v + 1
    integer, parameter :: sz = threadsFv%z
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  u
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  v
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  w
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: ux
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: vx
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: vz
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: wz
    integer i, j, k, it, jt, kt, jj, idx, offset_xz
    real(8) :: tyx, tyy, tyz, utyx, vtyy, wtyz, kTy
    #:if is_les
    real(8) Hsgs
    #:endif
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    #:if is_koff
    k  = (blockIdx%z-1)*blockDim%z + kt + k_lo - 1
    #:else
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    #:endif
    offset_xz = (it-1)*sy + (kt-1)*sy*sx
    #:if VISC_ORDER == 4
    call load_smem_visc_cent4_y(it, jt, kt, i, k, nx, ny, nz, dx, dz, Q, u, v, w, ux, vx, vz, wz)
    #:elif VISC_STENCIL == 'ME4Base'
    call load_smem_visc_me4_base_y(it, jt, kt, i, k, nx, ny, nz, dx, dz, Q, u, v, w, ux, vx, vz, wz)
    #:else
    call load_smem_visc_cent6_y(it, jt, kt, i, k, nx, ny, nz, dx, dz, Q, u, v, w, ux, vx, vz, wz)
    #:endif
    j  = (blockIdx%y-1)*blockDim%y + jt
    idx = jt + offset_xz
    #:if is_koff
    if (nx-1 < i .or. ny-1 < j .or. k_hi < k) return
    #:else
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return
    #:endif
    #:if VISC_ORDER == 4
    if (3 <= i .and. i <= nx-2 .and. 2 <= j .and. j <= ny-2 .and. 3 <= k .and. k <= nz-2) then
      block
        real(8) :: mu4(4), T4(4)
        #:if is_les
        real(8) :: mut4(4)
        mut4(:) = mut(i, j-1:j+2, k)
        #:endif
        mu4(:) = mu(i, j-1:j+2, k)
        T4(:) = T(i, j-1:j+2, k)
        kTy = Cp_over_Pr * interp4(mu4) * diff4(dy(j), T4)
        #:if is_les
        call calc_tau_straight_LES(mu4, mut4, v(idx-1:idx+2), wz(idx-1:idx+2), ux(idx-1:idx+2), dy(j), tyy, vtyy)
        call calc_tau_cross_LES(mu4, mut4, u(idx-1:idx+2), vx(idx-1:idx+2), dy(j), tyx, utyx)
        call calc_tau_cross_LES(mu4, mut4, w(idx-1:idx+2), vz(idx-1:idx+2), dy(j), tyz, wtyz)
        block
          real(8) :: H(4)
          H(:) = Cp * T(i,j-1:j+2,k) + 0.5d0 * (u(idx-1:idx+2)**2 + v(idx-1:idx+2)**2 + w(idx-1:idx+2)**2) + qc2(i,j-1:j+2,k)
          Hsgs = -interp4(mut4) * diff4(dy(j), H) / Prt
        end block
        #:else
        call calc_tau_straight(mu4, v(idx-1:idx+2), wz(idx-1:idx+2), ux(idx-1:idx+2), dy(j), tyy, vtyy)
        call calc_tau_cross(mu4, u(idx-1:idx+2), vx(idx-1:idx+2), dy(j), tyx, utyx)
        call calc_tau_cross(mu4, w(idx-1:idx+2), vz(idx-1:idx+2), dy(j), tyz, wtyz)
        #:endif
        F(2,i-1,j,k-1) = F(2,i-1,j,k-1) - tyx
        F(3,i-1,j,k-1) = F(3,i-1,j,k-1) - tyy
        F(4,i-1,j,k-1) = F(4,i-1,j,k-1) - tyz
        F(5,i-1,j,k-1) = F(5,i-1,j,k-1) - (utyx + vtyy + wtyz + kTy &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:elif VISC_STENCIL == 'ME4Base'
    if (3 <= i .and. i <= nx-2 .and. 3 <= j .and. j <= ny-3 .and. 3 <= k .and. k <= nz-2) then
      block
        real(8) :: mu3(3)
        #:if is_les
        real(8) :: mut3(3)
        mut3(:) = 0.0625d0 * (9.d0 * (mut(i,j-1:j+1,k) + mut(i,j:j+2,k)) - (mut(i,j-2:j,k) + mut(i,j+1:j+3,k)))
        #:endif
        mu3(:)  = 0.0625d0 * (9.d0 * ( mu(i,j-1:j+1,k) +  mu(i,j:j+2,k)) - ( mu(i,j-2:j,k) +  mu(i,j+1:j+3,k)))
        block ! dQdy
          real(8) :: kTy3(3)
          kTy3(:) = Cp_over_Pr * mu3(:) * &
                    (1.125d0 * (-T(i,j-1:j+1,k) + T(i,j:j+2,k)) - (-T(i,j-2:j,k) + T(i,j+1:j+3,k)) * one_24) * dy(j)
          kTy     = flux4(kTy3(:))
        end block
        #:if is_les
        call calc_tau_straight_LES(mu3, mut3, v(idx-2:idx+3), wz(idx-2:idx+3), ux(idx-2:idx+3), dy(j), tyy, vtyy)
        call calc_tau_cross_LES(mu3, mut3, u(idx-2:idx+3), vx(idx-2:idx+3), dy(j), tyx, utyx)
        call calc_tau_cross_LES(mu3, mut3, w(idx-2:idx+3), vz(idx-2:idx+3), dy(j), tyz, wtyz)
        block
          real(8) :: H(4)
          H(:) = Cp * T(i,j-1:j+2,k) + 0.5d0 * (u(idx-1:idx+2)**2 + v(idx-1:idx+2)**2 + w(idx-1:idx+2)**2) + qc2(i,j-1:j+2,k)
          Hsgs = -flux4(mut3) * (1.125d0 * (-H(2) + H(3)) - (-H(1) + H(4)) * one_24) * dy(j) / Prt
        end block
        #:else
        call calc_tau_straight(mu3, v(idx-2:idx+3), wz(idx-2:idx+3), ux(idx-2:idx+3), dy(j), tyy, vtyy)
        call calc_tau_cross(mu3, u(idx-2:idx+3), vx(idx-2:idx+3), dy(j), tyx, utyx)
        call calc_tau_cross(mu3, w(idx-2:idx+3), vz(idx-2:idx+3), dy(j), tyz, wtyz)
        #:endif
        F(2,i-1,j,k-1) = F(2,i-1,j,k-1) - tyx
        F(3,i-1,j,k-1) = F(3,i-1,j,k-1) - tyy
        F(4,i-1,j,k-1) = F(4,i-1,j,k-1) - tyz
        F(5,i-1,j,k-1) = F(5,i-1,j,k-1) - (utyx + vtyy + wtyz + kTy &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:else
    if (4 <= i .and. i <= nx-3 .and. 3 <= j .and. j <= ny-3 .and. 4 <= k .and. k <= nz-3) then
      block
        real(8) :: mu6(6), T6(6)
        #:if is_les
        real(8) :: mut6(6)
        mut6(:) = mut(i, j-2:j+3, k)
        #:endif
        mu6(:) = mu(i, j-2:j+3, k)
        T6(:) = T(i, j-2:j+3, k)
        kTy = Cp_over_Pr * interp6(mu6) * diff6(dy(j), T6)
        #:if is_les
        call calc_tau_straight_LES(mu6, mut6, v(idx-2:idx+3), wz(idx-2:idx+3), ux(idx-2:idx+3), dy(j), tyy, vtyy)
        call calc_tau_cross_LES(mu6, mut6, u(idx-2:idx+3), vx(idx-2:idx+3), dy(j), tyx, utyx)
        call calc_tau_cross_LES(mu6, mut6, w(idx-2:idx+3), vz(idx-2:idx+3), dy(j), tyz, wtyz)
        block
          real(8) :: H(6)
          H(:) = Cp * T(i,j-2:j+3,k) + 0.5d0 * (u(idx-2:idx+3)**2 + v(idx-2:idx+3)**2 + w(idx-2:idx+3)**2) + qc2(i,j-2:j+3,k)
          Hsgs = -interp6(mut6) * diff6(dy(j), H) / Prt
        end block
        #:else
        call calc_tau_straight(mu6, v(idx-2:idx+3), wz(idx-2:idx+3), ux(idx-2:idx+3), dy(j), tyy, vtyy)
        call calc_tau_cross(mu6, u(idx-2:idx+3), vx(idx-2:idx+3), dy(j), tyx, utyx)
        call calc_tau_cross(mu6, w(idx-2:idx+3), vz(idx-2:idx+3), dy(j), tyz, wtyz)
        #:endif
        F(2,i-1,j,k-1) = F(2,i-1,j,k-1) - tyx
        F(3,i-1,j,k-1) = F(3,i-1,j,k-1) - tyy
        F(4,i-1,j,k-1) = F(4,i-1,j,k-1) - tyz
        F(5,i-1,j,k-1) = F(5,i-1,j,k-1) - (utyx + vtyy + wtyz + kTy &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:endif
    endif
  end subroutine calc_Fv${VISC_ORDER}$${suf}$
#:endfor


#:for is_koff in [False, True]
  #:set suf = base_suf
  #:if is_koff
    #:set suf = suf + "_koff"
  #:endif
  attributes(global) subroutine calc_Gv${VISC_ORDER}$${suf}$(nx, ny, nz, dx, dy, dz, Q, T, mu, &
    #:if is_les
      mut, qc2, &
    #:endif
    #:if is_koff
      k_lo, k_hi, &
    #:endif
    G)
    integer, intent(in), value                 :: nx
    integer, intent(in), value                 :: ny
    integer, intent(in), value                 :: nz
    real(8), intent(in), device, contiguous    :: dx(nx-1)
    real(8), intent(in), device, contiguous    :: dy(ny-1)
    real(8), intent(in), device, contiguous    :: dz(nz-1)
    real(8), intent(in), device, contiguous    :: Q(nx,5,ny,nz)
    real(8), intent(in), device, contiguous    :: T(nx,ny,nz)
    real(8), intent(in), device, contiguous    :: mu(nx,ny,nz)
    #:if is_les
    real(8), intent(in), device, contiguous    :: mut(nx,ny,nz)
    real(8), intent(in), device, contiguous    :: qc2(nx,ny,nz)
    #:endif
    real(8), intent(inout), device, contiguous :: G(5,nx-2,ny-2,nz-1)
    #:if is_koff
    integer, intent(in), value                 :: k_lo
    integer, intent(in), value                 :: k_hi
    #:endif
    #:if VISC_ORDER == 4
    integer, parameter :: io_v = 1
    #:else
    integer, parameter :: io_v = 2
    #:endif
    integer, parameter :: sx = threadsGv%x
    integer, parameter :: sy = threadsGv%y
    integer, parameter :: sz = threadsGv%z + 2*io_v + 1
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  u
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  v
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared ::  w
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: wx
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: wy
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: ux
    real(8), dimension(-(io_v-1):sx*sy*sz-io_v), shared :: vy
    integer i, j, k, it, jt, kt, kk, idx, offset_xy
    real(8) :: tzx, tzy, tzz, utzx, vtzy, wtzz, kTz
    #:if is_les
    real(8) :: Hsgs
    #:endif
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    offset_xy = (jt-1)*sz + (it-1)*sz*sy
    #:if is_koff
    #:if VISC_ORDER == 4
    call load_smem_visc_cent4_z_koff(it, jt, kt, i, j, nx, ny, nz, dx, dy, Q, u, v, w, ux, wx, vy, wy, k_lo)
    #:elif VISC_STENCIL == 'ME4Base'
    call load_smem_visc_me4_base_z_koff(it, jt, kt, i, j, nx, ny, nz, dx, dy, Q, u, v, w, ux, wx, vy, wy, k_lo)
    #:else
    call load_smem_visc_cent6_z_koff(it, jt, kt, i, j, nx, ny, nz, dx, dy, Q, u, v, w, ux, wx, vy, wy, k_lo)
    #:endif
    k  = (blockIdx%z-1)*blockDim%z + k_lo - 1 + kt
    if (nx-1 < i .or. ny-1 < j .or. k_hi < k) return
    #:else
    #:if VISC_ORDER == 4
    call load_smem_visc_cent4_z(it, jt, kt, i, j, nx, ny, nz, dx, dy, Q, u, v, w, ux, wx, vy, wy)
    #:elif VISC_STENCIL == 'ME4Base'
    call load_smem_visc_me4_base_z(it, jt, kt, i, j, nx, ny, nz, dx, dy, Q, u, v, w, ux, wx, vy, wy)
    #:else
    call load_smem_visc_cent6_z(it, jt, kt, i, j, nx, ny, nz, dx, dy, Q, u, v, w, ux, wx, vy, wy)
    #:endif
    k  = (blockIdx%z-1)*blockDim%z + kt
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return
    #:endif
    idx = kt + offset_xy
    #:if VISC_ORDER == 4
    if (3 <= i .and. i <= nx-2 .and. 3 <= j .and. j <= ny-2 .and. 2 <= k .and. k <= nz-2) then
      block
        real(8) :: mu4(4), T4(4)
        #:if is_les
        real(8) :: mut4(4)
        mut4(:) = mut(i, j, k-1:k+2)
        #:endif
        mu4(:) = mu(i, j, k-1:k+2)
        T4(:) = T(i, j, k-1:k+2)
        kTz = Cp_over_Pr * interp4(mu4) * diff4(dz(k), T4)
        #:if is_les
        call calc_tau_straight_LES(mu4, mut4, w(idx-1:idx+2), ux(idx-1:idx+2), vy(idx-1:idx+2), dz(k), tzz, wtzz)
        call calc_tau_cross_LES(mu4, mut4, u(idx-1:idx+2), wx(idx-1:idx+2), dz(k), tzx, utzx)
        call calc_tau_cross_LES(mu4, mut4, v(idx-1:idx+2), wy(idx-1:idx+2), dz(k), tzy, vtzy)
        block
          real(8) :: H(4)
          H(:) = Cp * T(i,j,k-1:k+2) + 0.5d0 * (u(idx-1:idx+2)**2 + v(idx-1:idx+2)**2 + w(idx-1:idx+2)**2) + qc2(i,j,k-1:k+2)
          Hsgs = -interp4(mut4) * diff4(dz(k), H) / Prt
        end block
        #:else
        call calc_tau_straight(mu4, w(idx-1:idx+2), ux(idx-1:idx+2), vy(idx-1:idx+2), dz(k), tzz, wtzz)
        call calc_tau_cross(mu4, u(idx-1:idx+2), wx(idx-1:idx+2), dz(k), tzx, utzx)
        call calc_tau_cross(mu4, v(idx-1:idx+2), wy(idx-1:idx+2), dz(k), tzy, vtzy)
        #:endif
        G(2,i-1,j-1,k) = G(2,i-1,j-1,k) - tzx
        G(3,i-1,j-1,k) = G(3,i-1,j-1,k) - tzy
        G(4,i-1,j-1,k) = G(4,i-1,j-1,k) - tzz
        G(5,i-1,j-1,k) = G(5,i-1,j-1,k) - (utzx + vtzy + wtzz + kTz &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:elif VISC_STENCIL == 'ME4Base'
    if (3 <= i .and. i <= nx-2 .and. 3 <= j .and. j <= ny-2 .and. 3 <= k .and. k <= nz-3) then
      block
        real(8) :: mu3(3)
        #:if is_les
        real(8) :: mut3(3)
        mut3(:) = 0.0625d0 * (9.d0 * (mut(i,j,k-1:k+1) + mut(i,j,k:k+2)) - (mut(i,j,k-2:k) + mut(i,j,k+1:k+3)))
        #:endif
        mu3(:)  = 0.0625d0 * (9.d0 * ( mu(i,j,k-1:k+1) +  mu(i,j,k:k+2)) - ( mu(i,j,k-2:k) +  mu(i,j,k+1:k+3)))
        block ! dQdz
          real(8) :: kTz3(3)
          kTz3(:) = Cp_over_Pr * mu3(:) * &
                    (1.125d0 * (-T(i,j,k-1:k+1) + T(i,j,k:k+2)) - (-T(i,j,k-2:k) + T(i,j,k+1:k+3)) * one_24) * dz(k)
          kTz     = flux4(kTz3(:))
        end block
        #:if is_les
        call calc_tau_straight_LES(mu3, mut3, w(idx-2:idx+3), ux(idx-2:idx+3), vy(idx-2:idx+3), dz(k), tzz, wtzz)
        call calc_tau_cross_LES(mu3, mut3, u(idx-2:idx+3), wx(idx-2:idx+3), dz(k), tzx, utzx)
        call calc_tau_cross_LES(mu3, mut3, v(idx-2:idx+3), wy(idx-2:idx+3), dz(k), tzy, vtzy)
        block
          real(8) :: H(4)
          H(:) = Cp * T(i,j,k-1:k+2) + 0.5d0 * (u(idx-1:idx+2)**2 + v(idx-1:idx+2)**2 + w(idx-1:idx+2)**2) + qc2(i,j,k-1:k+2)
          Hsgs = -flux4(mut3) * (1.125d0 * (-H(2) + H(3)) - (-H(1) + H(4)) * one_24) * dz(k) / Prt
        end block
        #:else
        call calc_tau_straight(mu3, w(idx-2:idx+3), ux(idx-2:idx+3), vy(idx-2:idx+3), dz(k), tzz, wtzz)
        call calc_tau_cross(mu3, u(idx-2:idx+3), wx(idx-2:idx+3), dz(k), tzx, utzx)
        call calc_tau_cross(mu3, v(idx-2:idx+3), wy(idx-2:idx+3), dz(k), tzy, vtzy)
        #:endif
        G(2,i-1,j-1,k) = G(2,i-1,j-1,k) - tzx
        G(3,i-1,j-1,k) = G(3,i-1,j-1,k) - tzy
        G(4,i-1,j-1,k) = G(4,i-1,j-1,k) - tzz
        G(5,i-1,j-1,k) = G(5,i-1,j-1,k) - (utzx + vtzy + wtzz + kTz &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:else
    if (4 <= i .and. i <= nx-3 .and. 4 <= j .and. j <= ny-3 .and. 3 <= k .and. k <= nz-3) then
      block
        real(8) :: mu6(6), T6(6)
        #:if is_les
        real(8) :: mut6(6)
        mut6(:) = mut(i, j, k-2:k+3)
        #:endif
        mu6(:) = mu(i, j, k-2:k+3)
        T6(:) = T(i, j, k-2:k+3)
        kTz = Cp_over_Pr * interp6(mu6) * diff6(dz(k), T6)
        #:if is_les
        call calc_tau_straight_LES(mu6, mut6, w(idx-2:idx+3), ux(idx-2:idx+3), vy(idx-2:idx+3), dz(k), tzz, wtzz)
        call calc_tau_cross_LES(mu6, mut6, u(idx-2:idx+3), wx(idx-2:idx+3), dz(k), tzx, utzx)
        call calc_tau_cross_LES(mu6, mut6, v(idx-2:idx+3), wy(idx-2:idx+3), dz(k), tzy, vtzy)
        block
          real(8) :: H(6)
          H(:) = Cp * T(i,j,k-2:k+3) + 0.5d0 * (u(idx-2:idx+3)**2 + v(idx-2:idx+3)**2 + w(idx-2:idx+3)**2) + qc2(i,j,k-2:k+3)
          Hsgs = -interp6(mut6) * diff6(dz(k), H) / Prt
        end block
        #:else
        call calc_tau_straight(mu6, w(idx-2:idx+3), ux(idx-2:idx+3), vy(idx-2:idx+3), dz(k), tzz, wtzz)
        call calc_tau_cross(mu6, u(idx-2:idx+3), wx(idx-2:idx+3), dz(k), tzx, utzx)
        call calc_tau_cross(mu6, v(idx-2:idx+3), wy(idx-2:idx+3), dz(k), tzy, vtzy)
        #:endif
        G(2,i-1,j-1,k) = G(2,i-1,j-1,k) - tzx
        G(3,i-1,j-1,k) = G(3,i-1,j-1,k) - tzy
        G(4,i-1,j-1,k) = G(4,i-1,j-1,k) - tzz
        G(5,i-1,j-1,k) = G(5,i-1,j-1,k) - (utzx + vtzy + wtzz + kTz &
        #:if is_les
          + Hsgs &
        #:endif
        )
      end block
    #:endif
    endif
  end subroutine calc_Gv${VISC_ORDER}$${suf}$
#:endfor
end module calc_visc_high_internal
#:endif
