#:set N = VISC_ORDER
  attributes(device) function interp${N}$(a) result(ai)
    real(8), intent(in), contiguous :: a(${N}$)
    real(8) ai
    #:if N == 4
    block
      real(8) s1, s2
      !ai = 0.0625d0 * (-a(1) + 9.d0 * (a(2) + a(3)) - a(4))
      s1 = a(2) + a(3)
      s2 = a(1) + a(4)
      ai = 0.0625d0 * fma(9.d0, s1, -s2)
    end block
    #:else
    block
      real(8) s1, s2, s3, v
      !ai = 0.00390625d0 * (3.d0*a(1) - 25.d0*a(2) + 150.d0*(a(3)+a(4)) - 25.d0*a(5) + 3.d0*a(6))
      s1 = a(1) + a(6)
      s2 = a(2) + a(5)
      s3 = a(3) + a(4)
      v  = 0.01171875d0 * s1
      v  = fma(-0.09765625d0, s2, v)
      ai = fma(0.5859375d0,   s3, v)
    end block
    #:endif
  end function interp${N}$

  attributes(device) function diff${N}$(d, a) result(da)
    real(8), intent(in)             :: d
    real(8), intent(in), contiguous :: a(${N}$)
    real(8) da
    #:if N == 4
    block
      real(8) factor, s1, s2
      !da = (a(1) - 27.d0 * (a(2) - a(3)) - a(4)) * one_24 * d
      factor = one_24 * d
      s1 = a(2) - a(3)
      s2 = a(1) - a(4)
      da = factor * fma(-27.d0, s1, s2)
    end block
    #:else
    block
      real(8) s1, s2, s3, v
      !da = (-0.0046875d0*a(1) + 0.065104167d0*a(2) - 1.171875d0*(a(3)-a(4)) - 0.065104167d0*a(5) + 0.0046875d0*a(6)) * d
      s1 = -a(1) + a(6)
      s2 =  a(2) - a(5)
      s3 = -a(3) + a(4)
      v  = 0.0046875d0 * s1
      v  = fma(0.065104167d0, s2, v)
      da = d * fma(1.171875d0, s3, v)
    end block
    #:endif
  end function diff${N}$

  attributes(device) subroutine calc_tau_straight(mu, u, vy, wz, d, t11, ut11)
    real(8), intent(in), contiguous :: mu(${N}$)
    real(8), intent(in), contiguous :: u(${N}$)
    real(8), intent(in), contiguous :: vy(${N}$)
    real(8), intent(in), contiguous :: wz(${N}$)
    real(8), intent(in)             :: d
    real(8), intent(out)            :: t11
    real(8), intent(out)            :: ut11
    real(8) mui, vyi, wzi, ux
    mui  = interp${N}$(mu)
    vyi  = interp${N}$(vy)
    wzi  = interp${N}$(wz)
    ux   = diff${N}$(d, u)
    t11  = two_third * mui * (fma(2.d0, ux, -vyi - wzi))
    ut11 = interp${N}$(u) * t11
  end subroutine calc_tau_straight

  attributes(device) subroutine calc_tau_straight_LES(mu, mut, u, vy, wz, d, t11, ut11)
    real(8), intent(in), contiguous :: mu(${N}$)
    real(8), intent(in), contiguous :: mut(${N}$)
    real(8), intent(in), contiguous :: u(${N}$)
    real(8), intent(in), contiguous :: vy(${N}$)
    real(8), intent(in), contiguous :: wz(${N}$)
    real(8), intent(in)             :: d
    real(8), intent(out)            :: t11
    real(8), intent(out)            :: ut11
    real(8) mui, vyi, wzi, ux
    mui  = interp${N}$(mu)
    vyi  = interp${N}$(vy)
    wzi  = interp${N}$(wz)
    ux   = diff${N}$(d, u)
    t11  = two_third * mui * (fma(2.d0, ux, -vyi - wzi))
    ut11 = interp${N}$(u) * t11
    mui  = 0.5d0 * (mui + interp${N}$(mut))
    t11  = two_third * mui * (fma(2.d0, ux, -vyi - wzi))
  end subroutine calc_tau_straight_LES

  attributes(device) subroutine calc_tau_cross(mu, v, uy, d, t12, vt12)
    real(8), intent(in), contiguous :: mu(${N}$)
    real(8), intent(in), contiguous :: v(${N}$)
    real(8), intent(in), contiguous :: uy(${N}$)
    real(8), intent(in)             :: d
    real(8), intent(out)            :: t12
    real(8), intent(out)            :: vt12
    real(8) mui, uyi, vx
    mui  = interp${N}$(mu)
    uyi  = interp${N}$(uy)
    vx   = diff${N}$(d, v)
    t12  = mui * (uyi + vx)
    vt12 = interp${N}$(v) * t12
  end subroutine calc_tau_cross

  attributes(device) subroutine calc_tau_cross_LES(mu, mut, v, uy, d, t12, vt12)
    real(8), intent(in), contiguous :: mu(${N}$)
    real(8), intent(in), contiguous :: mut(${N}$)
    real(8), intent(in), contiguous :: v(${N}$)
    real(8), intent(in), contiguous :: uy(${N}$)
    real(8), intent(in)             :: d
    real(8), intent(out)            :: t12
    real(8), intent(out)            :: vt12
    real(8) mui, uyi, vx
    mui  = interp${N}$(mu)
    uyi  = interp${N}$(uy)
    vx   = diff${N}$(d, v)
    t12  = mui * (uyi + vx)
    vt12 = interp${N}$(v) * t12
    mui  = 0.5d0 * (mui + interp${N}$(mut))
    t12  = mui * (uyi + vx)
  end subroutine calc_tau_cross_LES
