#:include 'config.fypp'
#:if not defined('VISC_ORDER')
  #:set VISC_ORDER = ORDER
#:endif
#:set io_v_val = 1 if VISC_ORDER == 4 else 2
#:set D_MIN = 3 if VISC_ORDER == 4 else 4
#:set D_SFX = 2 if VISC_ORDER == 4 else 3

module load_smem_visc_cent${VISC_ORDER}$
  use wmma
  use mod_globals, only : threadsEv, threadsFv, threadsGv
  #:if VISC_ORDER == 4
  use mod_constant, only : two_third, one_twelfth
  #:else
  use mod_constant, only : one_sixty
  #:endif
  implicit none
  private
  public load_smem_visc_cent${VISC_ORDER}$_x, load_smem_visc_cent${VISC_ORDER}$_y, &
         load_smem_visc_cent${VISC_ORDER}$_z, load_smem_visc_cent${VISC_ORDER}$_z_koff
contains
  attributes(device) subroutine load_smem_visc_cent${VISC_ORDER}$_x(it, jt, kt, j, k, &
                                                       nx, ny, nz, inv_dy, inv_dz, Q, u, v, w, uy, vy, uz, wz)
    integer, intent(in), value              :: it
    integer, intent(in), value              :: jt
    integer, intent(in), value              :: kt
    integer, intent(in), value              :: j
    integer, intent(in), value              :: k
    integer, intent(in), value              :: nx
    integer, intent(in), value              :: ny
    integer, intent(in), value              :: nz
    real(8), intent(in), device, contiguous :: inv_dy(ny-1)
    real(8), intent(in), device, contiguous :: inv_dz(nz-1)
    real(8), intent(in), device, contiguous :: Q(nx,5,ny,nz)
    integer, parameter :: io_v = ${io_v_val}$
    integer, parameter :: sx = threadsEv%x + 2*io_v + 1
    integer, parameter :: sy = threadsEv%y
    integer, parameter :: sz = threadsEv%z
    real(8), intent(inout) ::  u(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  v(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  w(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: uy(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: vy(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: uz(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: wz(-(io_v-1):sx*sy*sz-io_v)
    integer i_base, ii, i, idx, offset_yz
    i_base = (blockIdx%x-1)*blockDim%x
    offset_yz = (jt-1)*sx + (kt-1)*sx*sy
    do ii = it-io_v, threadsEv%x+io_v+1, blockDim%x
      i = i_base + ii
      idx = ii + offset_yz
      if (1 <= i .and. i <= nx .and. j <= ny .and. k <= nz) then
        call pipelineMemcpyAsync(u(idx), Q(i,2,j,k))
        call pipelineMemcpyAsync(v(idx), Q(i,3,j,k))
        call pipelineMemcpyAsync(w(idx), Q(i,4,j,k))
      endif
    enddo
    call pipelineCommit()
    do ii = it-io_v, threadsEv%x+io_v+1, blockDim%x
      i = i_base + ii
      idx = ii + offset_yz
      if (1 <= i .and. i <= nx .and. ${D_MIN}$ <= j .and. j <= ny-${D_SFX}$ .and. k <= nz) then
#:if VISC_ORDER == 4
        uy(idx) = (two_third * (-Q(i,2,j-1,k) + Q(i,2,j+1,k)) - one_twelfth * (-Q(i,2,j-2,k) + Q(i,2,j+2,k))) * inv_dy(j)
        vy(idx) = (two_third * (-Q(i,3,j-1,k) + Q(i,3,j+1,k)) - one_twelfth * (-Q(i,3,j-2,k) + Q(i,3,j+2,k))) * inv_dy(j)
#:else
        uy(idx) = (one_sixty * (-Q(i,2,j-3,k) + Q(i,2,j+3,k)) + 0.15d0 * (Q(i,2,j-2,k) - Q(i,2,j+2,k)) + 0.75d0 * (-Q(i,2,j-1,k) + Q(i,2,j+1,k))) * inv_dy(j)
        vy(idx) = (one_sixty * (-Q(i,3,j-3,k) + Q(i,3,j+3,k)) + 0.15d0 * (Q(i,3,j-2,k) - Q(i,3,j+2,k)) + 0.75d0 * (-Q(i,3,j-1,k) + Q(i,3,j+1,k))) * inv_dy(j)
#:endif
      endif
      if (1 <= i .and. i <= nx .and. j <= ny .and. ${D_MIN}$ <= k .and. k <= nz-${D_SFX}$) then
#:if VISC_ORDER == 4
        uz(idx) = (two_third * (-Q(i,2,j,k-1) + Q(i,2,j,k+1)) - one_twelfth * (-Q(i,2,j,k-2) + Q(i,2,j,k+2))) * inv_dz(k)
        wz(idx) = (two_third * (-Q(i,4,j,k-1) + Q(i,4,j,k+1)) - one_twelfth * (-Q(i,4,j,k-2) + Q(i,4,j,k+2))) * inv_dz(k)
#:else
        uz(idx) = (one_sixty * (-Q(i,2,j,k-3) + Q(i,2,j,k+3)) + 0.15d0 * (Q(i,2,j,k-2) - Q(i,2,j,k+2)) + 0.75d0 * (-Q(i,2,j,k-1) + Q(i,2,j,k+1))) * inv_dz(k)
        wz(idx) = (one_sixty * (-Q(i,4,j,k-3) + Q(i,4,j,k+3)) + 0.15d0 * (Q(i,4,j,k-2) - Q(i,4,j,k+2)) + 0.75d0 * (-Q(i,4,j,k-1) + Q(i,4,j,k+1))) * inv_dz(k)
#:endif
      endif
    enddo
    call pipelineWaitPrior(0)
    call syncthreads()
  end subroutine load_smem_visc_cent${VISC_ORDER}$_x


  attributes(device) subroutine load_smem_visc_cent${VISC_ORDER}$_y(it, jt, kt, i, k, &
                                                       nx, ny, nz, inv_dx, inv_dz, Q, u, v, w, ux, vx, vz, wz)
    integer, intent(in), value              :: it
    integer, intent(in), value              :: jt
    integer, intent(in), value              :: kt
    integer, intent(in), value              :: i
    integer, intent(in), value              :: k
    integer, intent(in), value              :: nx
    integer, intent(in), value              :: ny
    integer, intent(in), value              :: nz
    real(8), intent(in), device, contiguous :: inv_dx(nx-1)
    real(8), intent(in), device, contiguous :: inv_dz(nz-1)
    real(8), intent(in), device, contiguous :: Q(nx,5,ny,nz)
    integer, parameter :: io_v = ${io_v_val}$
    integer, parameter :: sx = threadsFv%x
    integer, parameter :: sy = threadsFv%y + 2*io_v + 1
    integer, parameter :: sz = threadsFv%z
    real(8), intent(inout) ::  u(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  v(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  w(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: ux(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: vx(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: vz(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: wz(-(io_v-1):sx*sy*sz-io_v)
    integer j_base, jj, j, idx, offset_xz
    j_base = (blockIdx%y-1)*blockDim%y
    offset_xz = (it-1)*sy + (kt-1)*sy*sx
    do jj = jt-io_v, threadsFv%y+io_v+1, blockDim%y
      j = j_base + jj
      idx = jj + offset_xz
      if (i <= nx .and. 1 <= j .and. j <= ny .and. k <= nz) then
        call pipelineMemcpyAsync(u(idx), Q(i,2,j,k))
        call pipelineMemcpyAsync(v(idx), Q(i,3,j,k))
        call pipelineMemcpyAsync(w(idx), Q(i,4,j,k))
      endif
    enddo
    call pipelineCommit()
    do jj = jt-io_v, threadsFv%y+io_v+1, blockDim%y
      j = j_base + jj
      idx = jj + offset_xz
      if (${D_MIN}$ <= i .and. i <= nx-${D_SFX}$ .and. 1 <= j .and. j <= ny .and. k <= nz) then
#:if VISC_ORDER == 4
        ux(idx) = (two_third * (-Q(i-1,2,j,k) + Q(i+1,2,j,k)) - one_twelfth * (-Q(i-2,2,j,k) + Q(i+2,2,j,k))) * inv_dx(i)
        vx(idx) = (two_third * (-Q(i-1,3,j,k) + Q(i+1,3,j,k)) - one_twelfth * (-Q(i-2,3,j,k) + Q(i+2,3,j,k))) * inv_dx(i)
#:else
        ux(idx) = (one_sixty * (-Q(i-3,2,j,k) + Q(i+3,2,j,k)) + 0.15d0 * (Q(i-2,2,j,k) - Q(i+2,2,j,k)) + 0.75d0 * (-Q(i-1,2,j,k) + Q(i+1,2,j,k))) * inv_dx(i)
        vx(idx) = (one_sixty * (-Q(i-3,3,j,k) + Q(i+3,3,j,k)) + 0.15d0 * (Q(i-2,3,j,k) - Q(i+2,3,j,k)) + 0.75d0 * (-Q(i-1,3,j,k) + Q(i+1,3,j,k))) * inv_dx(i)
#:endif
      endif
      if (i <= nx .and. 1 <= j .and. j <= ny .and. ${D_MIN}$ <= k .and. k <= nz-${D_SFX}$) then
#:if VISC_ORDER == 4
        vz(idx) = (two_third * (-Q(i,3,j,k-1) + Q(i,3,j,k+1)) - one_twelfth * (-Q(i,3,j,k-2) + Q(i,3,j,k+2))) * inv_dz(k)
        wz(idx) = (two_third * (-Q(i,4,j,k-1) + Q(i,4,j,k+1)) - one_twelfth * (-Q(i,4,j,k-2) + Q(i,4,j,k+2))) * inv_dz(k)
#:else
        vz(idx) = (one_sixty * (-Q(i,3,j,k-3) + Q(i,3,j,k+3)) + 0.15d0 * (Q(i,3,j,k-2) - Q(i,3,j,k+2)) + 0.75d0 * (-Q(i,3,j,k-1) + Q(i,3,j,k+1))) * inv_dz(k)
        wz(idx) = (one_sixty * (-Q(i,4,j,k-3) + Q(i,4,j,k+3)) + 0.15d0 * (Q(i,4,j,k-2) - Q(i,4,j,k+2)) + 0.75d0 * (-Q(i,4,j,k-1) + Q(i,4,j,k+1))) * inv_dz(k)
#:endif
      endif
    enddo
    call pipelineWaitPrior(0)
    call syncthreads()
  end subroutine load_smem_visc_cent${VISC_ORDER}$_y


  attributes(device) subroutine load_smem_visc_cent${VISC_ORDER}$_z(it, jt, kt, i, j, &
                                                       nx, ny, nz, inv_dx, inv_dy, Q, u, v, w, ux, wx, vy, wy)
    integer, intent(in), value              :: it
    integer, intent(in), value              :: jt
    integer, intent(in), value              :: kt
    integer, intent(in), value              :: i
    integer, intent(in), value              :: j
    integer, intent(in), value              :: nx
    integer, intent(in), value              :: ny
    integer, intent(in), value              :: nz
    real(8), intent(in), device, contiguous :: inv_dx(nx-1)
    real(8), intent(in), device, contiguous :: inv_dy(ny-1)
    real(8), intent(in), device, contiguous :: Q(nx,5,ny,nz)
    integer, parameter :: io_v = ${io_v_val}$
    integer, parameter :: sx = threadsGv%x
    integer, parameter :: sy = threadsGv%y
    integer, parameter :: sz = threadsGv%z + 2*io_v + 1
    real(8), intent(inout) ::  u(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  v(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  w(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: ux(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: wx(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: vy(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: wy(-(io_v-1):sx*sy*sz-io_v)
    integer k_base, kk, k, idx, offset_xy
    k_base = (blockIdx%z-1)*blockDim%z
    offset_xy = (jt-1)*sz + (it-1)*sz*sy
    do kk = kt-io_v, threadsGv%z+io_v+1, blockDim%z
      k = k_base + kk
      idx = kk + offset_xy
      if (i <= nx .and. j <= ny .and. 1 <= k .and. k <= nz) then
        call pipelineMemcpyAsync(u(idx), Q(i,2,j,k))
        call pipelineMemcpyAsync(v(idx), Q(i,3,j,k))
        call pipelineMemcpyAsync(w(idx), Q(i,4,j,k))
      endif
    enddo
    call pipelineCommit()
    do kk = kt-io_v, threadsGv%z+io_v+1, blockDim%z
      k = k_base + kk
      idx = kk + offset_xy
      if (${D_MIN}$ <= i .and. i <= nx-${D_SFX}$ .and. j <= ny .and. 1 <= k .and. k <= nz) then
#:if VISC_ORDER == 4
        ux(idx) = (two_third * (-Q(i-1,2,j,k) + Q(i+1,2,j,k)) - one_twelfth * (-Q(i-2,2,j,k) + Q(i+2,2,j,k))) * inv_dx(i)
        wx(idx) = (two_third * (-Q(i-1,4,j,k) + Q(i+1,4,j,k)) - one_twelfth * (-Q(i-2,4,j,k) + Q(i+2,4,j,k))) * inv_dx(i)
#:else
        ux(idx) = (one_sixty * (-Q(i-3,2,j,k) + Q(i+3,2,j,k)) + 0.15d0 * (Q(i-2,2,j,k) - Q(i+2,2,j,k)) + 0.75d0 * (-Q(i-1,2,j,k) + Q(i+1,2,j,k))) * inv_dx(i)
        wx(idx) = (one_sixty * (-Q(i-3,4,j,k) + Q(i+3,4,j,k)) + 0.15d0 * (Q(i-2,4,j,k) - Q(i+2,4,j,k)) + 0.75d0 * (-Q(i-1,4,j,k) + Q(i+1,4,j,k))) * inv_dx(i)
#:endif
      endif
      if (i <= nx .and. ${D_MIN}$ <= j .and. j <= ny-${D_SFX}$ .and. 1 <= k .and. k <= nz) then
#:if VISC_ORDER == 4
        vy(idx) = (two_third * (-Q(i,3,j-1,k) + Q(i,3,j+1,k)) - one_twelfth * (-Q(i,3,j-2,k) + Q(i,3,j+2,k))) * inv_dy(j)
        wy(idx) = (two_third * (-Q(i,4,j-1,k) + Q(i,4,j+1,k)) - one_twelfth * (-Q(i,4,j-2,k) + Q(i,4,j+2,k))) * inv_dy(j)
#:else
        vy(idx) = (one_sixty * (-Q(i,3,j-3,k) + Q(i,3,j+3,k)) + 0.15d0 * (Q(i,3,j-2,k) - Q(i,3,j+2,k)) + 0.75d0 * (-Q(i,3,j-1,k) + Q(i,3,j+1,k))) * inv_dy(j)
        wy(idx) = (one_sixty * (-Q(i,4,j-3,k) + Q(i,4,j+3,k)) + 0.15d0 * (Q(i,4,j-2,k) - Q(i,4,j+2,k)) + 0.75d0 * (-Q(i,4,j-1,k) + Q(i,4,j+1,k))) * inv_dy(j)
#:endif
      endif
    enddo
    call pipelineWaitPrior(0)
    call syncthreads()
  end subroutine load_smem_visc_cent${VISC_ORDER}$_z


  attributes(device) subroutine load_smem_visc_cent${VISC_ORDER}$_z_koff(it, jt, kt, i, j, &
                                                            nx, ny, nz, inv_dx, inv_dy, Q, u, v, w, ux, wx, vy, wy, k_lo)
    integer, intent(in), value              :: it
    integer, intent(in), value              :: jt
    integer, intent(in), value              :: kt
    integer, intent(in), value              :: i
    integer, intent(in), value              :: j
    integer, intent(in), value              :: nx
    integer, intent(in), value              :: ny
    integer, intent(in), value              :: nz
    real(8), intent(in), device, contiguous :: inv_dx(nx-1)
    real(8), intent(in), device, contiguous :: inv_dy(ny-1)
    real(8), intent(in), device, contiguous :: Q(nx,5,ny,nz)
    integer, intent(in), value              :: k_lo
    integer, parameter :: io_v = ${io_v_val}$
    integer, parameter :: sx = threadsGv%x
    integer, parameter :: sy = threadsGv%y
    integer, parameter :: sz = threadsGv%z + 2*io_v + 1
    real(8), intent(inout) ::  u(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  v(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) ::  w(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: ux(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: wx(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: vy(-(io_v-1):sx*sy*sz-io_v)
    real(8), intent(inout) :: wy(-(io_v-1):sx*sy*sz-io_v)
    integer k_base, kk, k, idx, offset_xy
    k_base = (blockIdx%z-1)*blockDim%z + k_lo - 1
    offset_xy = (jt-1)*sz + (it-1)*sz*sy
    do kk = kt-io_v, threadsGv%z+io_v+1, blockDim%z
      k = k_base + kk
      idx = kk + offset_xy
      if (i <= nx .and. j <= ny .and. 1 <= k .and. k <= nz) then
        call pipelineMemcpyAsync(u(idx), Q(i,2,j,k))
        call pipelineMemcpyAsync(v(idx), Q(i,3,j,k))
        call pipelineMemcpyAsync(w(idx), Q(i,4,j,k))
      endif
    enddo
    call pipelineCommit()
    do kk = kt-io_v, threadsGv%z+io_v+1, blockDim%z
      k = k_base + kk
      idx = kk + offset_xy
      if (${D_MIN}$ <= i .and. i <= nx-${D_SFX}$ .and. j <= ny .and. 1 <= k .and. k <= nz) then
#:if VISC_ORDER == 4
        ux(idx) = (two_third * (-Q(i-1,2,j,k) + Q(i+1,2,j,k)) - one_twelfth * (-Q(i-2,2,j,k) + Q(i+2,2,j,k))) * inv_dx(i)
        wx(idx) = (two_third * (-Q(i-1,4,j,k) + Q(i+1,4,j,k)) - one_twelfth * (-Q(i-2,4,j,k) + Q(i+2,4,j,k))) * inv_dx(i)
#:else
        ux(idx) = (one_sixty * (-Q(i-3,2,j,k) + Q(i+3,2,j,k)) + 0.15d0 * (Q(i-2,2,j,k) - Q(i+2,2,j,k)) + 0.75d0 * (-Q(i-1,2,j,k) + Q(i+1,2,j,k))) * inv_dx(i)
        wx(idx) = (one_sixty * (-Q(i-3,4,j,k) + Q(i+3,4,j,k)) + 0.15d0 * (Q(i-2,4,j,k) - Q(i+2,4,j,k)) + 0.75d0 * (-Q(i-1,4,j,k) + Q(i+1,4,j,k))) * inv_dx(i)
#:endif
      endif
      if (i <= nx .and. ${D_MIN}$ <= j .and. j <= ny-${D_SFX}$ .and. 1 <= k .and. k <= nz) then
#:if VISC_ORDER == 4
        vy(idx) = (two_third * (-Q(i,3,j-1,k) + Q(i,3,j+1,k)) - one_twelfth * (-Q(i,3,j-2,k) + Q(i,3,j+2,k))) * inv_dy(j)
        wy(idx) = (two_third * (-Q(i,4,j-1,k) + Q(i,4,j+1,k)) - one_twelfth * (-Q(i,4,j-2,k) + Q(i,4,j+2,k))) * inv_dy(j)
#:else
        vy(idx) = (one_sixty * (-Q(i,3,j-3,k) + Q(i,3,j+3,k)) + 0.15d0 * (Q(i,3,j-2,k) - Q(i,3,j+2,k)) + 0.75d0 * (-Q(i,3,j-1,k) + Q(i,3,j+1,k))) * inv_dy(j)
        wy(idx) = (one_sixty * (-Q(i,4,j-3,k) + Q(i,4,j+3,k)) + 0.15d0 * (Q(i,4,j-2,k) - Q(i,4,j+2,k)) + 0.75d0 * (-Q(i,4,j-1,k) + Q(i,4,j+1,k))) * inv_dy(j)
#:endif
      endif
    enddo
    call pipelineWaitPrior(0)
    call syncthreads()
  end subroutine load_smem_visc_cent${VISC_ORDER}$_z_koff
end module load_smem_visc_cent${VISC_ORDER}$
