#:include 'config.fypp'
module calc_hybrid_kernel
  use mod_globals, only : gamma, sp, threshold, threadsE, threadsF, threadsG
  use mod_constant, only : id_slau, over_gamma_1_ff, R_over_gamma_1_ff, one_third_ff, one_sixth_ff, one_twelfth_ff, two_third_ff, &
                           c0_25_ff, c0_5_ff, c1_ff, c2_ff, gamma_over_gamma_1_ff, &
                           c0_375_ff, c0_075_ff, c0_1875_ff, c0_0375_ff, c8_ff, c37_ff, c0_75_ff, c0_15_ff
  use calc_muscl
  use calc_hybrid
  use fltflt
  use cudadevice
  implicit none
  private
  public calc_hybrid_x, calc_hybrid_y, calc_hybrid_z
  include 'fltflt_operator_interfaces.f90'
  include 'fltflt_subroutines_interfaces.f90'
  real(8), parameter :: one_24        = 1.d0 / 24.d0
  real(8), parameter :: one_48        = 1.d0 / 48.d0
  real(8), parameter :: one_60        = 1.d0 / 60.d0
  real(8), parameter :: one_120       = 1.d0 / 120.d0
  real(8), parameter :: one_240       = 1.d0 / 240.d0
  real(8), parameter :: seven_twelfth = 7.d0 / 12.d0
  integer, parameter :: io            = ${ORDER_IO}$

  #:if ORDER == 6
  integer(8), parameter :: id_acc   = 0_8
  integer(4), parameter :: id_acc4 = 0_4
  integer(2), parameter :: id_acc2 = 0_2
  #:elif ORDER == 4
  integer(4), parameter :: id_acc   = 0_4
  integer(2), parameter :: id_acc2 = 0_2
  #:else
  integer(2), parameter :: id_acc   = 0_2
  #:endif

  interface KEEP
    module procedure KEEP2_ff, KEEP4_ff, KEEP6_ff
  end interface KEEP

  interface SLAU
    module procedure SLAU1_ff, HRSLAU2_ff
  end interface SLAU
contains
  include 'fltflt_operator.f90'
  include 'fltflt_subroutines.f90'
  include 'calc_keep_3d_ff.f90'
  include 'calc_slau_3d_ff.f90'

  attributes(global) subroutine calc_hybrid_x(nx, ny, nz, Q, T, sensor, E)
    use mod_constant, only : Normal_x_ff
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q(nx,5,ny,nz), T(nx,ny,nz)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: E(5,nx-1,ny-2,nz-2)
    integer i, j, k, it, jt, kt, ii, i_base
    integer :: idx, offset_yz
    integer, parameter :: sx = threadsE%x + 2*io + 1
    integer, parameter :: sy = threadsE%y
    integer, parameter :: sz = threadsE%z
    type(fltflt), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p
    type(fltflt) :: rhol, ul, vl, wl, pl
    type(fltflt) :: rho_r, u_r, v_r, w_r, p_r
    real(sp) :: fdx
    logical  :: compute_slau
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    i_base = (blockIdx%x-1)*blockDim%x
    offset_yz = (jt-1) * sx + (kt-1) * sx * sy

    do ii = it-io, threadsE%x+io+1, blockDim%x
      i = i_base + ii
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny .and. k >= 1 .and. k <= nz) then
        idx = ii + offset_yz
        rho(idx) = fltflt_init(Q(i,1,j,k)); u(idx) = fltflt_init(Q(i,2,j,k)); v(idx) = fltflt_init(Q(i,3,j,k))
        w(idx)   = fltflt_init(Q(i,4,j,k)); p(idx) = fltflt_init(Q(i,5,j,k))
      endif
    enddo
    call syncthreads()

    i = (blockIdx%x-1)*blockDim%x + it
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return

    fdx = 0.5_sp * (sensor(i,j,k) + sensor(i+1,j,k))
    idx = it + offset_yz
    compute_slau = .false.

    #:if ORDER == 6
    if (3 <= i .and. i <= nx-3) then
      if (fdx <= threshold) then
        block
          type(fltflt) :: tmp(6)
          integer :: itmp
          do itmp = 1, 6
            tmp(itmp) = fltflt_init(T(i-3+itmp,j,k))
          enddo
          E(:,i,j-1,k-1) = KEEP(id_acc,      rho(idx-2:idx+3), u(idx-2:idx+3), v(idx-2:idx+3), &
                                w(idx-2:idx+3), u(idx-2:idx+3), p(idx-2:idx+3), tmp, Normal_x_ff)
        end block
      else
        call delta6(fdx, rho(idx-2:idx+3), rhol, rho_r)
        call delta6(fdx,   u(idx-2:idx+3),   ul,   u_r)
        call delta6(fdx,   v(idx-2:idx+3),   vl,   v_r)
        call delta6(fdx,   w(idx-2:idx+3),   wl,   w_r)
        call delta6(fdx,   p(idx-2:idx+3),   pl,   p_r)
        compute_slau = .true.
      endif
    elseif (2 <= i .and. i <= nx-2) then
      if (fdx <= threshold) then
        block
          type(fltflt) :: tmp(4)
          integer :: itmp
          do itmp = 1, 4
            tmp(itmp) = fltflt_init(T(i-2+itmp,j,k))
          enddo
          E(:,i,j-1,k-1) = KEEP(id_acc4,     rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                w(idx-1:idx+2), u(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_x_ff)
        end block
      else
        call delta4(fdx, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdx,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdx,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdx,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdx,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdx <= threshold) then
        block
          type(fltflt) :: tmp(2)
          integer :: itmp
          do itmp = 1, 2
            tmp(itmp) = fltflt_init(T(i-1+itmp,j,k))
          enddo
          E(:,i,j-1,k-1) = KEEP(id_acc2,   rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), u(idx:idx+1), p(idx:idx+1), tmp, Normal_x_ff)
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:elif ORDER == 4
    if (2 <= i .and. i <= nx-2) then
      if (fdx <= threshold) then
        block
          type(fltflt) :: tmp(4)
          integer :: itmp
          do itmp = 1, 4
            tmp(itmp) = fltflt_init(T(i-2+itmp,j,k))
          enddo
          E(:,i,j-1,k-1) = KEEP(id_acc,      rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                w(idx-1:idx+2), u(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_x_ff)
        end block
      else
        call delta4(fdx, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdx,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdx,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdx,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdx,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdx <= threshold) then
        block
          type(fltflt) :: tmp(2)
          integer :: itmp
          do itmp = 1, 2
            tmp(itmp) = fltflt_init(T(i-1+itmp,j,k))
          enddo
          E(:,i,j-1,k-1) = KEEP(id_acc2,   rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), u(idx:idx+1), p(idx:idx+1), tmp, Normal_x_ff)
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:else
    if (fdx <= threshold) then
      block
        type(fltflt) :: tmp(2)
        integer :: itmp
        do itmp = 1, 2
          tmp(itmp) = fltflt_init(T(i-1+itmp,j,k))
        enddo
        E(:,i,j-1,k-1) = KEEP(id_acc,    rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                              w(idx:idx+1), u(idx:idx+1), p(idx:idx+1), tmp, Normal_x_ff)
      end block
    else
      rhol = rho(idx); rho_r = rho(idx+1)
      ul   =   u(idx);   u_r =   u(idx+1)
      vl   =   v(idx);   v_r =   v(idx+1)
      wl   =   w(idx);   w_r =   w(idx+1)
      pl   =   p(idx);   p_r =   p(idx+1)
      compute_slau = .true.
    endif
    #:endif

    if (compute_slau) then
      associate(un1 => ul, un2 => u_r)
        call SLAU(id_slau, rhol, rho_r, ul, u_r, vl, v_r, wl, w_r, un1, un2, pl, p_r, Normal_x_ff, 1.0_sp, &
                  E(1,i,j-1,k-1), E(2,i,j-1,k-1), E(3,i,j-1,k-1), E(4,i,j-1,k-1), E(5,i,j-1,k-1))
      end associate
    endif
  end subroutine calc_hybrid_x


  attributes(global) subroutine calc_hybrid_y(nx, ny, nz, Q, T, sensor, F)
    use mod_constant, only : Normal_y_ff
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q(nx,5,ny,nz), T(nx,ny,nz)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: F(5,nx-2,ny-1,nz-2)
    integer i, j, k, it, jt, kt, jj, j_base
    integer :: idx, offset_xz
    integer, parameter :: sx = threadsF%x
    integer, parameter :: sy = threadsF%y + 2*io + 1
    integer, parameter :: sz = threadsF%z
    type(fltflt), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p
    type(fltflt) :: rhol, ul, vl, wl, pl
    type(fltflt) :: rho_r, u_r, v_r, w_r, p_r
    real(sp) :: fdy
    logical  :: compute_slau
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    j_base = (blockIdx%y-1)*blockDim%y
    offset_xz = (it-1) * sy + (kt-1) * sy * sx

    do jj = jt-io, threadsF%y+io+1, blockDim%y
      j = j_base + jj
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny .and. k >= 1 .and. k <= nz) then
        idx = jj + offset_xz
        rho(idx) = fltflt_init(Q(i,1,j,k)); u(idx) = fltflt_init(Q(i,2,j,k)); v(idx) = fltflt_init(Q(i,3,j,k))
        w(idx)   = fltflt_init(Q(i,4,j,k)); p(idx) = fltflt_init(Q(i,5,j,k))
      endif
    enddo
    call syncthreads()

    j = (blockIdx%y-1)*blockDim%y + jt
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return

    fdy = 0.5_sp * (sensor(i,j,k) + sensor(i,j+1,k))
    idx = jt + offset_xz
    compute_slau = .false.

    #:if ORDER == 6
    if (3 <= j .and. j <= ny-3) then
      if (fdy <= threshold) then
        block
          type(fltflt) :: tmp(6)
          integer :: itmp
          do itmp = 1, 6
            tmp(itmp) = fltflt_init(T(i,j-3+itmp,k))
          enddo
          F(:,i-1,j,k-1) = KEEP(id_acc,      rho(idx-2:idx+3), u(idx-2:idx+3), v(idx-2:idx+3), &
                                w(idx-2:idx+3), v(idx-2:idx+3), p(idx-2:idx+3), tmp, Normal_y_ff)
        end block
      else
        call delta6(fdy, rho(idx-2:idx+3), rhol, rho_r)
        call delta6(fdy,   u(idx-2:idx+3),   ul,   u_r)
        call delta6(fdy,   v(idx-2:idx+3),   vl,   v_r)
        call delta6(fdy,   w(idx-2:idx+3),   wl,   w_r)
        call delta6(fdy,   p(idx-2:idx+3),   pl,   p_r)
        compute_slau = .true.
      endif
    elseif (2 <= j .and. j <= ny-2) then
      if (fdy <= threshold) then
        block
          type(fltflt) :: tmp(4)
          integer :: itmp
          do itmp = 1, 4
            tmp(itmp) = fltflt_init(T(i,j-2+itmp,k))
          enddo
          F(:,i-1,j,k-1) = KEEP(id_acc4,     rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                w(idx-1:idx+2), v(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_y_ff)
        end block
      else
        call delta4(fdy, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdy,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdy,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdy,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdy,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdy <= threshold) then
        block
          type(fltflt) :: tmp(2)
          integer :: itmp
          do itmp = 1, 2
            tmp(itmp) = fltflt_init(T(i,j-1+itmp,k))
          enddo
          F(:,i-1,j,k-1) = KEEP(id_acc2,   rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), v(idx:idx+1), p(idx:idx+1), tmp, Normal_y_ff)
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:elif ORDER == 4
    if (2 <= j .and. j <= ny-2) then
      if (fdy <= threshold) then
        block
          type(fltflt) :: tmp(4)
          integer :: itmp
          do itmp = 1, 4
            tmp(itmp) = fltflt_init(T(i,j-2+itmp,k))
          enddo
          F(:,i-1,j,k-1) = KEEP(id_acc,      rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                w(idx-1:idx+2), v(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_y_ff)
        end block
      else
        call delta4(fdy, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdy,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdy,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdy,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdy,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdy <= threshold) then
        block
          type(fltflt) :: tmp(2)
          integer :: itmp
          do itmp = 1, 2
            tmp(itmp) = fltflt_init(T(i,j-1+itmp,k))
          enddo
          F(:,i-1,j,k-1) = KEEP(id_acc2,   rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), v(idx:idx+1), p(idx:idx+1), tmp, Normal_y_ff)
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:else
    if (fdy <= threshold) then
      block
        type(fltflt) :: tmp(2)
        integer :: itmp
        do itmp = 1, 2
          tmp(itmp) = fltflt_init(T(i,j-1+itmp,k))
        enddo
        F(:,i-1,j,k-1) = KEEP(id_acc,    rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                              w(idx:idx+1), v(idx:idx+1), p(idx:idx+1), tmp, Normal_y_ff)
      end block
    else
      rhol = rho(idx); rho_r = rho(idx+1)
      ul   =   u(idx);   u_r =   u(idx+1)
      vl   =   v(idx);   v_r =   v(idx+1)
      wl   =   w(idx);   w_r =   w(idx+1)
      pl   =   p(idx);   p_r =   p(idx+1)
      compute_slau = .true.
    endif
    #:endif

    if (compute_slau) then
      associate(un1 => vl, un2 => v_r)
        call SLAU(id_slau, rhol, rho_r, ul, u_r, vl, v_r, wl, w_r, un1, un2, pl, p_r, Normal_y_ff, 1.0_sp, &
                  F(1,i-1,j,k-1), F(2,i-1,j,k-1), F(3,i-1,j,k-1), F(4,i-1,j,k-1), F(5,i-1,j,k-1))
      end associate
    endif
  end subroutine calc_hybrid_y


  attributes(global) subroutine calc_hybrid_z(nx, ny, nz, Q, T, sensor, G)
    use mod_constant, only : Normal_z_ff
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q(nx,5,ny,nz), T(nx,ny,nz)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: G(5,nx-2,ny-2,nz-1)
    integer i, j, k, it, jt, kt, kk, k_base
    integer :: idx, offset_xy
    integer, parameter :: sx = threadsG%x
    integer, parameter :: sy = threadsG%y
    integer, parameter :: sz = threadsG%z + 2*io + 1
    type(fltflt), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p
    type(fltflt) :: rhol, ul, vl, wl, pl
    type(fltflt) :: rho_r, u_r, v_r, w_r, p_r
    real(sp) :: fdz
    logical  :: compute_slau
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    k_base = (blockIdx%z-1)*blockDim%z
    offset_xy = (jt-1) * sz + (it-1) * sz * sy

    do kk = kt-io, threadsG%z+io+1, blockDim%z
      k = k_base + kk
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny .and. k >= 1 .and. k <= nz) then
        idx = kk + offset_xy
        rho(idx) = fltflt_init(Q(i,1,j,k)); u(idx) = fltflt_init(Q(i,2,j,k)); v(idx) = fltflt_init(Q(i,3,j,k))
        w(idx)   = fltflt_init(Q(i,4,j,k)); p(idx) = fltflt_init(Q(i,5,j,k))
      endif
    enddo
    call syncthreads()

    k = (blockIdx%z-1)*blockDim%z + kt
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return

    fdz = 0.5_sp * (sensor(i,j,k) + sensor(i,j,k+1))
    idx = kt + offset_xy
    compute_slau = .false.

    #:if ORDER == 6
    if (3 <= k .and. k <= nz-3) then
      if (fdz <= threshold) then
        block
          type(fltflt) :: tmp(6)
          integer :: itmp
          do itmp = 1, 6
            tmp(itmp) = fltflt_init(T(i,j,k-3+itmp))
          enddo
          G(:,i-1,j-1,k) = KEEP(id_acc,      rho(idx-2:idx+3), u(idx-2:idx+3), v(idx-2:idx+3), &
                                w(idx-2:idx+3), w(idx-2:idx+3), p(idx-2:idx+3), tmp, Normal_z_ff)
        end block
      else
        call delta6(fdz, rho(idx-2:idx+3), rhol, rho_r)
        call delta6(fdz,   u(idx-2:idx+3),   ul,   u_r)
        call delta6(fdz,   v(idx-2:idx+3),   vl,   v_r)
        call delta6(fdz,   w(idx-2:idx+3),   wl,   w_r)
        call delta6(fdz,   p(idx-2:idx+3),   pl,   p_r)
        compute_slau = .true.
      endif
    elseif (2 <= k .and. k <= nz-2) then
      if (fdz <= threshold) then
        block
          type(fltflt) :: tmp(4)
          integer :: itmp
          do itmp = 1, 4
            tmp(itmp) = fltflt_init(T(i,j,k-2+itmp))
          enddo
          G(:,i-1,j-1,k) = KEEP(id_acc4,     rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                w(idx-1:idx+2), w(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_z_ff)
        end block
      else
        call delta4(fdz, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdz,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdz,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdz,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdz,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdz <= threshold) then
        block
          type(fltflt) :: tmp(2)
          integer :: itmp
          do itmp = 1, 2
            tmp(itmp) = fltflt_init(T(i,j,k-1+itmp))
          enddo
          G(:,i-1,j-1,k) = KEEP(id_acc2,   rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), w(idx:idx+1), p(idx:idx+1), tmp, Normal_z_ff)
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:elif ORDER == 4
    if (2 <= k .and. k <= nz-2) then
      if (fdz <= threshold) then
        block
          type(fltflt) :: tmp(4)
          integer :: itmp
          do itmp = 1, 4
            tmp(itmp) = fltflt_init(T(i,j,k-2+itmp))
          enddo
          G(:,i-1,j-1,k) = KEEP(id_acc,      rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                w(idx-1:idx+2), w(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_z_ff)
        end block
      else
        call delta4(fdz, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdz,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdz,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdz,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdz,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdz <= threshold) then
        block
          type(fltflt) :: tmp(2)
          integer :: itmp
          do itmp = 1, 2
            tmp(itmp) = fltflt_init(T(i,j,k-1+itmp))
          enddo
          G(:,i-1,j-1,k) = KEEP(id_acc2,   rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), w(idx:idx+1), p(idx:idx+1), tmp, Normal_z_ff)
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:else
    if (fdz <= threshold) then
      block
        type(fltflt) :: tmp(2)
        integer :: itmp
        do itmp = 1, 2
          tmp(itmp) = fltflt_init(T(i,j,k-1+itmp))
        enddo
        G(:,i-1,j-1,k) = KEEP(id_acc,    rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                              w(idx:idx+1), w(idx:idx+1), p(idx:idx+1), tmp, Normal_z_ff)
      end block
    else
      rhol = rho(idx); rho_r = rho(idx+1)
      ul   =   u(idx);   u_r =   u(idx+1)
      vl   =   v(idx);   v_r =   v(idx+1)
      wl   =   w(idx);   w_r =   w(idx+1)
      pl   =   p(idx);   p_r =   p(idx+1)
      compute_slau = .true.
    endif
    #:endif

    if (compute_slau) then
      associate(un1 => wl, un2 => w_r)
        call SLAU(id_slau, rhol, rho_r, ul, u_r, vl, v_r, wl, w_r, un1, un2, pl, p_r, Normal_z_ff, 1.0_sp, &
                  G(1,i-1,j-1,k), G(2,i-1,j-1,k), G(3,i-1,j-1,k), G(4,i-1,j-1,k), G(5,i-1,j-1,k))
      end associate
    endif
  end subroutine calc_hybrid_z
end module calc_hybrid_kernel
