module calc_flux
  use calc_term
  implicit none
contains
  attributes(device) subroutine calcE(nx, ny, nz, gamma, rho, u, v, w, p, dE)
    integer, intent(in), value :: nx, ny, nz
    real(8), intent(in), value :: gamma
    real(8), intent(in), dimension(nx,ny,nz) :: rho, u, v, w, p
    real(8), intent(out), dimension(nx-4,ny,nz,5) :: dE
    integer :: i, j, k
    real(8), dimension(3) :: rho_d, u_d, v_d, w_d, p_d 
    real(8), dimension(3) :: P_keep, RhoU, RhoUU, RhoUV, RhoUW, IE, RhoUIE, RhoUKE, UP, RhoUU_P, E_total
    real(8), dimension(nx-3,ny,nz,5) :: E
    do k = 1, nz
      do j = 1, ny
        do i = 1, nx-3
          rho_d = rho(i:i+3,j,k)
          u_d = u(i:i+3,j,k)
          v_d = v(i:i+3,j,k)
          w_d = w(i:i+3,j,k)
          p_d = p(i:i+3,j,k)
          call calc_Phi(p_d, P_keep)
          call calc_RhoPhi(rho_d, u_d, RhoU)
          call calc_RhoPhiU(RhoU, u_d, RhoUU)
          call calc_RhoPhiU(RhoU, v_d, RhoUV)
          call calc_RhoPhiU(RhoU, w_d, RhoUW)
          IE = p_d / ((gamma - 1.d0) * rho_d)
          call calc_RhoPhiU(RhoU, IE, RhoUIE)
          call calc_RhoUPhi2(RhoU, u_d, v_d, w_d, RhoUKE)
          call calc_PhiPsi(u_d, p_d, UP)
          call merge_term(RhoU, E(i,j,k,1))
          RhoUU_P = RhoUU + P_keep
          call merge_term(RhoUU_P, E(i,j,k,2))
          call merge_term(RhoUV, E(i,j,k,3))
          call merge_term(RhoUW, E(i,j,k,4))
          E_total = RhoUIE + RhoUKE + UP
          call merge_term(E_total, E(i,j,k,5))
        enddo
      enddo
    enddo
    dE = -E(1:nx-4,:,:,:) + E(2:nx-3,:,:,:)
  end subroutine calcE

  attributes(device) subroutine calcF(nx, ny, nz, gamma, rho, u, v, w, p, dF)
    integer, intent(in), value :: nx, ny, nz
    real(8), intent(in), value :: gamma
    real(8), intent(in), dimension(nx,ny,nz) :: rho, u, v, w, p
    real(8), intent(out) :: dF(nx,ny-4,nz,5)
    integer :: i, j, k
    real(8), dimension(3) :: rho_d, u_d, v_d, w_d, p_d 
    real(8), dimension(3) :: P_keep, RhoV, RhoVU, RhoVV, RhoVW, IE, RhoVIE, RhoVKE, VP, RhoVV_P, E_total
    real(8), dimension(nx,ny-3,nz,5) :: F
    do k = 1, nz
      do j = 1, ny-3
        do i = 1, nx
          rho_d = rho(i,j:j+3,k)
          u_d = u(i,j:j+3,k)
          v_d = v(i,j:j+3,k)
          w_d = w(i,j:j+3,k)
          p_d = p(i,j:j+3,k)
          call calc_Phi(p_d, P_keep)
          call calc_RhoPhi(rho_d, v_d, RhoV)
          call calc_RhoPhiU(RhoV, u_d, RhoVU)
          call calc_RhoPhiU(RhoV, v_d, RhoVV)
          call calc_RhoPhiU(RhoV, w_d, RhoVW)
          IE = p_d / ((gamma - 1.0d0) * rho_d)
          call calc_RhoPhiU(RhoV, IE, RhoVIE)
          call calc_RhoUPhi2(RhoV, u_d, v_d, w_d, RhoVKE)
          call calc_PhiPsi(v_d, p_d, VP)
          call merge_term(RhoV, F(i,j,k,1))
          call merge_term(RhoVU, F(i,j,k,2))
          RhoVV_P = RhoVV + P_keep
          call merge_term(RhoVV_P, F(i,j,k,3))
          call merge_term(RHoVW, F(i,j,k,4))
          E_total = RhoVIE + RhoVKE + VP
          call merge_term(E_total, F(i,j,k,5))
        enddo
      enddo
    enddo
    dF = -F(:,1:ny-4,:,:) + F(:,2:ny-3,:,:)
  end subroutine calcF

  attributes(device) subroutine calcG(nx, ny, nz, gamma, rho, u, v, w, p, dG)
    integer, intent(in), value :: nx, ny, nz
    real(8), intent(in), value :: gamma
    real(8), intent(in), dimension(nx,ny,nz) :: rho, u, v, w, p
    real(8), intent(out) :: dG(nx,ny,nz-4,5)
    integer :: i, j, k
    real(8), dimension(3) :: rho_d, u_d, v_d, w_d, p_d 
    real(8), dimension(3) :: P_keep, RhoW, RhoWU, RhoWV, RhoWW, IE, RhoWIE, RhoWKE, WP, RhoWW_P, E_total
    real(8), dimension(nx,ny,nz-3,5) :: G
    do k = 1, nz-3
      do j = 1, ny
        do i = 1, nx
          rho_d = rho(i,j,k:k+3)
          u_d = u(i,j,k:k+3)
          v_d = v(i,j,k:k+3)
          w_d = w(i,j,k:k+3)
          p_d = p(i,j,k:k+3)
          call calc_Phi(p_d, P_keep)
          call calc_RhoPhi(rho_d, w_d, RhoW)
          call calc_RhoPhiU(RhoW, u_d, RhoWU)
          call calc_RhoPhiU(RhoW, v_d, RhoWV)
          call calc_RhoPhiU(RhoW, w_d, RhoWW)
          IE = p_d / ((gamma - 1.d0) * rho_d)
          call calc_RhoPhiU(RhoW, IE, RhoWIE)
          call calc_RhoUPhi2(RhoW, u_d, v_d, w_d, RhoWKE)
          call calc_PhiPsi(w_d, p_d, WP)
          call merge_term(RhoW, G(i,j,k,1))
          call merge_term(RhoWU, G(i,j,k,2))
          call merge_term(RhoWV, G(i,j,k,3))
          RhoWW_P = RhoWW + P_keep
          call merge_term(RhoWW_P, G(i,j,k,4))
          E_total = RhoWIE + RhoWKE + WP
          call merge_term(E_total, G(i,j,k,5))
        enddo
      enddo
    enddo
    dG = -G(:,:,1:nz-4,:) + G(:,:,2:nz-3,:)
  end subroutine calcG

  attributes(device) subroutine calc_EFG(nx, ny, nz, dX, dY, dZ, gamma, mu, kappa, Cp, Q, R)
    integer, intent(in), value :: nx, ny, nz
    real(8), intent(in), value :: dX, dY, dZ, gamma, mu, kappa, Cp
    real(8), intent(in) :: Q(nx,ny,nz,5)
    real(8), intent(out) :: R(nx-4,ny-4,nz-4,5)
    real(8), dimension(nx,ny,nz) :: rho, u, v, w, p!, T
    real(8), dimension(nx-4,ny-4,nz-4,5) :: dE, dF, dG
    real(8), dimension(nx,ny-4,nz-4) :: rhox, ux, vx, wx, px
    real(8), dimension(nx-4,ny,nz-4) :: rhoy, uy, vy, wy, py
    real(8), dimension(nx-4,ny-4,nz) :: rhoz, uz, vz, wz, pz
    rho = Q(:,:,:,1)
    u = Q(:,:,:,2) / rho
    v = Q(:,:,:,3) / rho
    w = Q(:,:,:,4) / rho
    p = (gamma - 1.d0) * (Q(:,:,:,5) - 0.5d0 * rho * (u ** 2 + v ** 2 + w ** 2))
    !T = ((Q(:,:,:,5) + p) / rho - 0.5d0 * (u ** 2 + v ** 2 + w ** 2)) / Cp
    
    rhox = rho(:,3:ny-2,3:nz-2)
    ux = u(:,3:ny-2,3:nz-2)
    vx = v(:,3:ny-2,3:nz-2)
    wx = w(:,3:ny-2,3:nz-2)
    px = p(:,3:ny-2,3:nz-2)
    rhoy = rho(3:nx-2,:,3:nz-2)
    uy = u(3:nx-2,:,3:nz-2)
    vy = v(3:nx-2,:,3:nz-2)
    wy = w(3:nx-2,:,3:nz-2)
    py = p(3:nx-2,:,3:nz-2)
    rhoz = rho(3:nx-2,3:ny-2,:)
    uz = u(3:nx-2,3:ny-2,:)
    vz = v(3:nx-2,3:ny-2,:)
    wz = w(3:nx-2,3:ny-2,:)
    pz = p(3:nx-2,3:ny-2,:)

    call calcE(nx, ny-4, nz-4, gamma, rhox, ux, vx, wx, px, dE)
    call calcF(nx-4, ny, nz-4, gamma, rhoy, uy, vy, wy, py, dF)
    call calcG(nx-4, ny-4, nz, gamma, rhoz, uz, vz, wz, pz, dG)

    R = dX * dE + dY * dF + dZ * dG
  end subroutine calc_EFG
end module calc_flux
