module calc_time_dev
  implicit none
contains
  subroutine RungeKutta(nx,ny,nz,nyp,nzp,nt,np,dx,dy,dz,dt,gamma,mu,kappa,Cp,Q)
    use cudafor
    use calc_steps
    use set_bc
    use print
    ! CPU
    integer, intent(in) :: nx, ny, nz, nyp, nzp, nt, np
    real(8), intent(in) :: dx, dy, dz, dt, gamma, mu, kappa, Cp
    real(8), intent(inout) :: Q(nx,nyp,nzp,5,4)
    real(8), dimension(nx,nyp,nzp,5,4) :: Q2, Q3
    integer t, tp, ni, nj, nk, threadIdx, threadIdy, threadIdz, stat
    ! GPU
    type(dim3) :: blocks, threads
    integer, device :: nx_d, ny_d, nz_d, nyp_d, nzp_d, ni_d, nj_d, nk_d
    attributes(constant) :: nx_d, ny_d, nz_d, nyp_d, nzp_d, ni_d, nj_d, nk_d
    real(8), device :: dx_d, dy_d, dz_d, dt_d, gamma_d, mu_d, kappa_d, Cp_d
    attributes(constant) :: dx_d, dy_d, dz_d, dt_d, gamma_d, mu_d, kappa_d, Cp_d
    real(8), dimension(nx,nyp,nzp,5,4), device :: Q_d, Q2_d, Q3_d
    
    ! define block size
    ! 14 * 14 * 14 = 2744 threads
    threadIdx = 14
    threadIdy = 14
    threadIdz = 14
    ni = (nz - 4) / threadIdx
    nj = (ny - 4) / threadIdy
    nk = (nz - 4) / threadIdz
    if (mod(nx-4,ni)/=0 .or. mod(nyp-4,nj)/=0 .or. mod(nzp-4,nk)/=0 .or. ni<5 .or. nj<5 .or. nk<5) then
      write(*,*) 'Cannot split properly'
      stop
    endif
    blocks = dim3(4,1,1)
    threads = dim3(threadIdx, threadIdy, threadIdz)
    
    ! send variables to GPU
    nx_d = nx
    ny_d = ny
    nz_d = nz
    nyp_d = nyp
    nzp_d = nzp
    ni_d = ni
    nj_d = nj
    nk_d = nk
    dx_d = 1.d0 / dx
    dy_d = 1.d0 / dy
    dz_d = 1.d0 / dz
    dt_d = dt
    gamma_d = gamma
    mu_d = mu
    kappa_d = kappa
    Cp_d = Cp
    Q_d = Q
    do tp = 1, np
      do t = 1, nt
        ! GPU
        call calc_step1<<<blocks, threads>>>(nx_d,nyp_d,nzp_d,ni_d,nj_d,nk_d,dx_d,dy_d,dz_d,dt_d,gamma_d,mu_d,kappa_d,Cp_d,Q_d,Q2_d)
        stat = cudaDeviceSynchronize()
        call set_cyclic_bc_d(nx,nyp,nzp,Q2_d)
        
        call calc_step2<<<blocks, threads>>>(nx_d,nyp_d,nzp_d,ni_d,nj_d,nk_d,dx_d,dy_d,dz_d,dt_d,gamma_d,mu_d,kappa_d,Cp_d,Q_d,Q2_d,Q3_d)
        stat = cudaDeviceSynchronize()
        call set_cyclic_bc_d(nx,nyp,nzp,Q3_d)
        
        call calc_step3<<<blocks, threads>>>(nx_d,nyp_d,nzp_d,ni_d,nj_d,nk_d,dx_d,dy_d,dz_d,dt_d,gamma_d,mu_d,kappa_d,Cp_d,Q3_d,Q_d)
        stat = cudaDeviceSynchronize()
        call set_cyclic_bc_d(nx,nyp,nzp,Q_d)
      enddo
      ! CPU
      Q = Q_d
      call print_vtk(tp,nx,ny,nz,nyp,nzp,dx,dy,dz,gamma,Q)
    enddo
    stat = cudaFree(Q_d)
    stat = cudaFree(Q2_d)
    stat = cudaFree(Q3_d)
  end subroutine RungeKutta
end module calc_time_dev
