module calc_steps
  implicit none
contains
  attributes(global) subroutine calc_step1(nx,ny,nz,ni,nj,nk,dX,dY,dZ,dt,gamma,mu,kappa,Cp,Q,Q2)
    use calc_flux
    integer, intent(in), value :: nx, ny, nz, ni, nj, nk
    real(8), intent(in), value :: dX, dY, dZ, dt, gamma, mu, kappa, Cp
    real(8), intent(in), dimension(nx,ny,nz,5,4) :: Q
    real(8), intent(inout), dimension(nx,ny,nz,5,4) :: Q2
    integer :: i, j, k
    real(8) :: Q_d(ni+4,nj+4,nk+4,5)
    real(8) :: R(ni,nj,nk,5)
    k = 3 + nk * (threadIdx%z - 1) !k = 3, nz-nk-1, nk :3 <= k <= nz-2
    j = 3 + nj * (threadIdx%y - 1) !j = 3, ny-nj-1, nj :3 <= j <= ny-2
    i = 3 + ni * (threadIdx%x - 1) !i = 3, nx-ni-1, ni :3 <= i <= nx-2
    Q_d = Q(i-2:i+ni+1,j-2:j+nj+1,k-2:k+nk+1,:,blockIdx%x)
    call calc_EFG(ni+4,nj+4,nk+4,dX,dY,dZ,gamma,mu,kappa,Cp,Q_d,R)
    Q2(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x) = Q(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x) - dt * R 
  end subroutine calc_step1
  
  attributes(global) subroutine calc_step2(nx,ny,nz,ni,nj,nk,dX,dY,dZ,dt,gamma,mu,kappa,Cp,Q,Q2,Q3)
    use calc_flux
    integer, intent(in), value :: nx, ny, nz, ni, nj, nk
    real(8), intent(in), value :: dX, dY, dZ, dt, gamma, mu, kappa, Cp
    real(8), intent(in), dimension(nx,ny,nz,5,4) :: Q, Q2
    real(8), intent(inout), dimension(nx,ny,nz,5,4) :: Q3
    integer :: i, j, k
    real(8) :: Q_d(ni+4,nj+4,nk+4,5)
    real(8) :: R(ni,nj,nk,5)
    k = 3 + nk * (threadIdx%z - 1) !k = 3, nz-nk-1, nk :3 <= k <= nz-2
    j = 3 + nj * (threadIdx%y - 1) !j = 3, ny-nj-1, nj :3 <= j <= ny-2
    i = 3 + ni * (threadIdx%x - 1) !i = 3, nx-ni-1, ni :3 <= i <= nx-2
    Q_d = Q2(i-2:i+ni+1,j-2:j+nj+1,k-2:k+nk+1,:,blockIdx%x)
    call calc_EFG(ni+4,nj+4,nk+4,dX,dY,dZ,gamma,mu,kappa,Cp,Q_d,R)
    Q3(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x) = 0.75d0 * Q(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x)&
    + 0.25d0 * Q2(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x) - 0.25d0 * dt * R
  end subroutine calc_step2
  
  attributes(global) subroutine calc_step3(nx,ny,nz,ni,nj,nk,dX,dY,dZ,dt,gamma,mu,kappa,Cp,Q3,Q)
    use calc_flux
    integer, intent(in), value :: nx, ny, nz, ni, nj, nk
    real(8), intent(in), value :: dX, dY, dZ, dt, gamma, mu, kappa, Cp
    real(8), intent(in), dimension(nx,ny,nz,5,4) :: Q3
    real(8), intent(inout), dimension(nx,ny,nz,5,4) :: Q
    integer :: i, j, k
    real(8) :: Q_d(ni+4,nj+4,nk+4,5)
    real(8) :: R(ni,nj,nk,5)
    k = 3 + nk * (threadIdx%z - 1) !k = 3, nz-nk-1, nk :3 <= k <= nz-2 
    j = 3 + nj * (threadIdx%y - 1) !j = 3, ny-nj-1, nj :3 <= j <= ny-2
    i = 3 + ni * (threadIdx%x - 1) !i = 3, nx-ni-1, ni :3 <= i <= nx-2
    Q_d = Q3(i-2:i+ni+1,j-2:j+nj+1,k-2:k+nk+1,:,blockIdx%x)
    call calc_EFG(ni+4,nj+4,nk+4,dX,dY,dZ,gamma,mu,kappa,Cp,Q_d,R)
    Q(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x) = (Q(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x)&
    + 2.0d0 * Q3(i:i+ni-1,j:j+nj-1,k:k+nk-1,:,blockIdx%x) - 2.0d0 * dt * R) / 3.d0
  end subroutine calc_step3
end module calc_steps
