name: HPC SDK Build

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 1. HPC SDKがインストール済みの公式コンテナを使用
    container:
      image: nvcr.io/nvidia/nvhpc:24.3-devel-cuda12.3-ubuntu22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 3D_solver のビルド
      - name: Build 3D_solver
        shell: bash
        run: |
          # Environment Modulesを有効化するためにsourceが必要
          . /etc/profile.d/modules.sh
          module load nvhpc-hpcx
          
          # 指定のディレクトリに移動してビルド
          cd 3D_solver/NSTGV
          make

      # 3. 3D_solver_curv のビルド
      - name: Build 3D_solver_curv
        shell: bash
        run: |
          . /etc/profile.d/modules.sh
          module load nvhpc-hpcx
          
          # 指定のディレクトリに移動してビルド
          cd 3D_solver_curv/NACA
          make
