name: HPC SDK Build

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Use Nvidia's container
    container:
      image: nvcr.io/nvidia/nvhpc:24.3-devel-cuda12.3-ubuntu22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MPI path
        run: |
          MPI_DIR=$(find /opt/nvidia/hpc_sdk -type d -path "*/comm_libs/mpi/bin" | head -n 1)
          echo "MPI_DIR=$MPI_DIR"

          echo "$MPI_DIR" >> $GITHUB_PATH

          which mpif90
          mpif90 --version

      - name: Build 3D_solver
        shell: bash
        run: |
          cd 3D_solver/NSTGV
          make

      - name: Build 3D_solver_curv
        shell: bash
        run: |
          cd 3D_solver_curv/NACA
          make
